### ISSUE TITLE
garbage collection card not updating 

### ISSUE THREAD

**Issue by Elplubio** [amaximus/garbage-collection-card#101]
- Home Assistant 2022.12.8
- garbage-collection-card installed via HACS

As seen in other post, I've removed the trailling "?hacstag=xxxxxxxxxxxxxxx" ( in manage ressources) but nothing changed.
The remaining days were good at time of installation but never update.

Screenshot of today 30 december, day of collect, still says collect is in two days
![image](https://user-images.githubusercontent.com/88271109/210104139-882333d6-e4df-4b32-95f4-d12524dc87b3.png)

configuration of card :
            type: vertical-stack
            cards:
              - type: custom:garbage-collection-card
                entity: sensor.poubelles
                icon_size: 50px
                icon_color: black
                hide_date: false
              - type: custom:garbage-collection-card
                entity: sensor.pmc
                icon_size: 50px
                icon_color: lightblue
                hide_date: false
              - type: custom:garbage-collection-card
                entity: sensor.papiers_cartons
                icon_size: 50px
                icon_color: orange
                hide_date: false

Browser used is chrome but same view on android HA apps
Garbage collection and garbage collection cards removed and re-install with no change.

Can someone point me to the place to look ?
Thanks

**Comment by amaximus** [comment]
Please make sure the sensors' state updated, e.g. for due today it should be 0 (for due tomorrow it should be 1, otherwise 2).

**Comment by Elplubio** [comment]
Thanks, you pointed to the problem.
States and attributes are not changing on the sensors.

So problem must relevant to garbage collector and not your card.
I'll look at this side now to resolve my problem

Thanks for your work and your expertise.
Wish you all and your families an happy new year
