### ISSUE TITLE
[FeatureRequest] automatically hide card on due day

### ISSUE THREAD

**Issue by Pimentoso** [amaximus/garbage-collection-card#102]
**Is your feature request related to a problem? Please describe.**
My area requires you put out garbage after 8pm on the day before, and they collect it very early at morning. So I have no use of a card for "today" because the garbage has already been collected, just the one for "tomorrow"

**Describe the solution you'd like**
I'd like a parameter that's something like `hide_on_today` that will hide the card when the due date is today.

Thanks!

**Comment by amaximus** [comment]
Implemented in the newest release: 1.22.0

Please update the card and get back to me with results.

**Comment by krzysiek2788** [comment]
Hi this update broke hide_before I have updated card and it is showing now all even if there is 16 days till due day:
![image](https://user-images.githubusercontent.com/61471407/211383544-ddd29a20-c5b6-4988-874f-55b4946ce555.png)
![image](https://user-images.githubusercontent.com/61471407/211383578-e2084e74-7fe3-4503-8bb9-39a8cb4ae492.png)

**Comment by amaximus** [comment]
Thanks for the heads-up @krzysiek2788 

I just released a fix for it.
Please update the card and get back to me with results.

**Comment by krzysiek2788** [comment]
@amaximus I update it just now and all is working with **hide_before**
I have due day tomorrow so I will update you tomorrow if **hide_on_today** is working as well

**Comment by michele-ferri-iubenda** [comment]
@amaximus thanks a lot for the quick response, I updated to 1.22.1 and `hide_on_today` is working flawlessly.
