### ISSUE TITLE
[BUG] how does due_txt work now?

### ISSUE THREAD

**Issue by Pimentoso** [amaximus/garbage-collection-card#105]
**Describe the bug**
I cannot get the `due_txt` to show with the latest version. This config showed "tomorrow" correctly the day before collection
```
type: custom:garbage-collection-card
entity: sensor.compostable
icon_size: 35px
icon_color: '#7c3a0d'
hide_on_click: false
hide_before: 1
hide_on_today: true
```

But now this config shows "02/22/2023 in 1 days" instead of "tomorrow"

I tried adding `hide_days` and/or `hide_date` and explicitly adding `due_txt` but it does not show.

**Screenshots**
![Screenshot 2023-02-21 at 21 57 38](https://user-images.githubusercontent.com/6085909/220457145-45cbf9a6-d03f-46f6-8917-3e01fe4301a7.png)

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.22.4
 - Browser: chrome
 - Browser language: english

**Comment by amaximus** [comment]
Did you try `due_txt: true`?
Please make sure the sensor doesn't use verbose_state: true.

**Comment by Pimentoso** [comment]
@amaximus ah sorry I misread the option. I thought it was to override the text with a custom one. `due_txt: true` works fine!
