### ISSUE TITLE
[FeatureRequest] Day of the week

### ISSUE THREAD

**Issue by woody4165** [amaximus/garbage-collection-card#107]
Hi 

Is there a way to show day of the week, possibly in local language?

Thanks

**Comment by amaximus** [comment]
Hi,

I just published a new release (1.23.0) adding support for displaying day of the week.

Please update the card and get back to me with results..

Thanks.

**Comment by woody4165** [comment]
Thanks @amaximus
I've tried, setting `hide_dow: false` and leaving the `dow_format` to default, but I get Invalid date 

![image](https://user-images.githubusercontent.com/6501444/225098315-e2b7c0c7-c7f9-4eca-9e4d-b160c9fffd16.png)

```
type: custom:garbage-collection-card
entity: sensor.raccolta_umido
hide_before: 1
icon_size: 35px
icon_color: brown
hide_dow: false

```


PS: I've tried also with `dow_format: "short"` but I get same error

**Comment by amaximus** [comment]
I just pushed a new release fixing this issue.

Please update your card and get back to me with results.

**Comment by woody4165** [comment]
@amaximus fantastic.
It's working fine now and it's my local language!
Thanks

**Comment by amaximus** [comment]
Thanks for the confirmation.
