### ISSUE TITLE
[BUG] Wrong italian translation

### ISSUE THREAD

**Issue by Suxsem** [amaximus/garbage-collection-card#109]
Hello, I'm italian and my native language is italian,
the italian translation for the "due" string is wrong.
Instead of "Da fare" should be "Per".

Can you please update the italian strings like so?
      "due": "per",
      "Due": "Per",

Many thanks!

**Comment by amaximus** [comment]
Thanks for the heads-up.

I just pushed a new release fixing the Italian translation.

Please update your card and get back to me with results.

**Comment by Suxsem** [comment]
@amaximus Perfect! Thank you!
