### ISSUE TITLE
So sad that you decide to stop this nice card

### ISSUE THREAD

**Issue by Electronlibre2012** [amaximus/garbage-collection-card#112]
**Is your feature request related to a problem? Please describe.**
Hello,

the local calendar doesnt create any sensor, so its so bad that you decide to remove your card, who is really daily helpfull and usefull...

Why not just maintenaid, which is your absolte right, but not remove please...

Thanks

Olivier

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by amaximus** [comment]
Please note that I didn't five up on the card and it will not be removed. You may have referred to the custom integration that was created by bruxy.

**Comment by Electronlibre2012** [comment]
sorry...my bad...

**Comment by amaximus** [comment]
No problem.
