### ISSUE TITLE
[FeatureRequest] adopt towards "hacs_waste_collection_schedule" since garbage-collection is deprecated

### ISSUE THREAD

**Issue by sir106** [amaximus/garbage-collection-card#114]
since garbage-collection custom component has been deprecated in 2023, please adopt (or enhance) the garbage-collection-card to integrate with hacs_waste_collection_schedule (https://github.com/mampfes/hacs_waste_collection_schedule)

Waste Collection Schedule is a custom component for Home Assistant that retrieves waste collection schedules from a wide range of service providers.

Unfortunately the lovelace garbage collection card is only supported with a workaround mentioned in the FAQ (https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/faq.md).

**Comment by amaximus** [comment]
I just pushed release 1.24.0 adding limited support for hacs_waste_collection_schedule.

Please check the README on what's supported as the custom integration provides a lot of flexibility.

Please update the card and get back to me with results.

**Comment by sir106** [comment]
works like a charm!! thank you!!!! now it's again as easy as before...

**Comment by putz612** [comment]
Would it be possible to provide screenshot of how you setup the custom component?

**Comment by amaximus** [comment]
@putz612 the README's last paragraph has an example how to set up hacs_waste_collection_schedule sensor to be compatible with this card. As for the card you'll have to set `source` to hacs_waste_collection_schedule.
