### ISSUE TITLE
hide_before isn't hiding the card

### ISSUE THREAD

**Issue by pvillanyi** [amaximus/garbage-collection-card#117]
**Describe the bug**
I wanted to show the cards just 3 days before due date, but hide_befor isn't affecting it.

**To Reproduce**
type: custom:garbage-collection-card
entity: sensor.zold_hulladek
icon_size: 35px
icon_color: green
due_1_color: green
due_color: red
hide_before: 3

**Expected behavior**
cards shouldn't be shown.

**Screenshots**
![image](https://github.com/amaximus/garbage-collection-card/assets/99245307/98b04193-7d73-427a-9730-ea88277b2879)

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.24.1
 - Browser: chrome and HA Companion
 - Browser language: HUN and ENG

**Additional context**

**Comment by amaximus** [comment]
The hide_before works the following way:
https://github.com/amaximus/garbage-collection-card/blob/master/dist/garbage-collection-card.js#L278

so for `hide_before: 3` it will hide the card if the attribute `days` is greater than 3.
See an example from today: both test_garbage_every_tue and test_garbage_every_wed have `hide_before: 3`, Tue sensor is displayed while Wed sensor is hidden:
![garbage](https://github.com/amaximus/garbage-collection-card/assets/2511168/701b6db9-4749-46b0-a9c5-1ebfc6d6713a)
```
(ha_venv3_12) pi@raspberrypi:~/homeassistant_test $grep -v "#" ui-lovelace.yaml | head -30|tail -18
      - type: custom:garbage-collection-card
        entity: sensor.test_garbage_every_tue
        icon_color: green
        icon_size: 35px
        hide_date: false
        hide_days: false
        due_txt: true
        hass_lang_priority: true
        hide_before: 3
      - type: custom:garbage-collection-card
        entity: sensor.test_garbage_every_wed
        icon_size: 35px
        hide_date: false
        hide_days: false
        due_txt: true
        due_1_color: brown
        due_color: red
        hide_before: 3
(ha_venv3_12) pi@raspberrypi:~/homeassistant_test $
```

**Comment by pvillanyi** [comment]
OK, it's nice you can use it.
Have you and idea, what could be wrong in my card config?
You can see, hide_before: 3 for zold_hulladek and the card is shown although it has 26 days.

**Comment by amaximus** [comment]
I will check tomorrow for green garbage as well.

**Comment by pvillanyi** [comment]
I use custom sensors with waste collection schedule.
It is a simple sensor in matters for garbage collection card.
But in my case neighter of the three cards hides when days are bigger than the set number in hide_before...

________________________________
Feladó: Atticus Maximus ***@***.***>
Elküldve: 2024. március 10., vasárnap 19:25
Címzett: amaximus/garbage-collection-card ***@***.***>
Másolatot kap: pvillanyi ***@***.***>; Author ***@***.***>
Tárgy: Re: [amaximus/garbage-collection-card] hide_before isn't hiding the card (Issue #117)


I will check tomorrow for green garbage as well.

**Comment by amaximus** [comment]
Please paste here the card configuration for the zold_hulladek sensor.

**Comment by pvillanyi** [comment]
As shown on top:

type: custom:garbage-collection-card
entity: sensor.zold_hulladek
icon_size: 35px
icon_color: green
due_1_color: green
due_color: red
hide_before: 3

**Comment by amaximus** [comment]
Could you please also provide a screenshot of the sensor.zoldhulladek as seen in the Developer Tools->States where the attributes are also seen.

**Comment by pvillanyi** [comment]
![image](https://github.com/amaximus/garbage-collection-card/assets/99245307/fa9d20e6-c639-4a91-9c1e-13b052aa6c19)

**Comment by amaximus** [comment]
The issue is that - as the Readme also mentions - it was written for bruxy70's Garbage Collection integration, meaning that it expects states and attributes as per that integration, e.g. state=0 (collection today), 1 (collection tomorrow) or 2 (collection later) and the `days` attribute among others:
![garbage1](https://github.com/amaximus/garbage-collection-card/assets/2511168/0724369d-f134-4dc2-b724-99369d0e4884)
If these cannot be found, the card will not work properly.

The Readme also mentions the card in what conditions supports the HACS Waste Collection Schedule integration. Check it out!

**Comment by pvillanyi** [comment]
I've changed the sensor configuration back to value_template: "{{ value.daysTo }}" and it works now although in developper tools it still doesn't show the days:

**Comment by pvillanyi** [comment]
the original was: value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'

**Comment by amaximus** [comment]
The simple format of `"{{ value.daysTo }}"` should be used for the sensor definition together with 
```
platform: waste_collection_schedule
details_format: 'generic'
```
See the example at the bottom of the Readme.
