### ISSUE TITLE
Garbage card no longer showing days or dates

### ISSUE THREAD

**Issue by mcinnes01** [amaximus/garbage-collection-card#12]
Hi the card is no longer showing any values for date or days. I've confirmed that the sensors are working as expected by using the sensor card instead, and can see:

Black Refuse on 03-Dec-2019, in 4 days

But when I use the garbage collection card I'm getting nothing now. I've tried with numerous combinations of hide_date and hide_day to no avail.

I'm seeing this error in the console when I add the garbage collection card:

create-card-element.ts:76 hui-sensor-card Error: Specify an entity from within the sensor domain.
    at HTMLElement.value (hui-sensor-card.ts:162)
    at ma (create-card-element.ts:73)
    at va (create-card-element.ts:124)
    at HTMLElement._createCard (hui-card-preview.ts:71)
    at HTMLElement.set config [as config] (hui-card-preview.ts:65)
    at m.commit (parts.js:368)
    at b.commit (parts.js:111)
    at o.update (template-instance.js:40)
    at f.__commitTemplateResult (parts.js:236)
    at f.commit (parts.js:186)

**Comment by amaximus** [comment]
Hi,

hui-sensor-card has nothing to do with the garbage collection card.
Could you please post your ui-lovelace part where you configure the garbage-collection-card?
What version of the garbage-collection-card are you using? (its latest version is 86febaa). Was it installed via HACS? While you report that the card doesn't show any date or days, are icons and/or titles shown?
Are you using the garbage-collection platform with verbose_state set to yes?
Was the garbage-collection platform installed via HACS?

**Comment by amaximus** [comment]
Update my config with the garbage-collection platform from HACS (on the top of an older version installed directly from github some time ago) and the garbage collection cards are gone now :( , home-assistant.log throws errors on setting up the garbage_collection platform:

2019-11-29 13:37:56 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform garbage_collection
Traceback (most recent call last):
  File "/home/pi/ha_venv3_7/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/pi/homeassistant_conf/custom_components/garbage_collection/sensor.py", line 57, in async_setup_platform
    async_add_entities([GarbageCollection(hass, discovery_info)], True)
  File "/home/pi/homeassistant_conf/custom_components/garbage_collection/sensor.py", line 115, in __init__
    self.__name = config.get(CONF_NAME)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by bschatzow** [comment]
It also stopped working for me.  Not sure if it was after a HA or garbage update.   I play some more today and see if I can get more information for you.

**Comment by amaximus** [comment]
Please make sure in the Developer Tools->States that you see your sensors.
I just learned that there was a breaking change in the garbage-collection custom component.

**Comment by bschatzow** [comment]
All 4 are seen in the developer tools states.  I have tried an easy add to the lovelace ui

```- type: custom:garbage-collection-card
        entity: sensor.garbage
        icon_size: 35px
        icon_color: green
        hide_date: true

When I add this Overview goes to blank.  Deleting the custom garbage collection card restores the overview.  Prior to one of the updates from this we I had in my lovelace file:

          - entity: sensor.garbage
            icon_color: brown
            icon_size: 35px
            type: 'custom:garbage-collection-card'
          - entity: sensor.garbage_2
            icon_color: brown
            icon_size: 35px
            type: 'custom:garbage-collection-card'
          - entity: sensor.recycle_2
            icon_color: brown
            icon_size: 35px
            type: 'custom:garbage-collection-card'
          - entity: sensor.branches_2
            icon_color: green
            icon_size: 35px
            type: 'custom:garbage-collection-card'
          - entity: sensor.yard_waste_2
            icon_color: green
            icon_size: 35px
            type: 'custom:garbage-collection-card'
        type: vertical-stack

I can use the garbage collection as entities.  

entities:
  - entity: sensor.yard_waste_2
  - entity: sensor.branches_2
  - entity: sensor.garbage
  - entity: sensor.recycle_2
show_header_toggle: true
title: front yard
type: entities

Not sure which update cause the problem as garbage collections has went through a few upgrades at the same time that HA upgraded.

**Comment by bschatzow** [comment]
Working again after 102.3 update
