### ISSUE TITLE
Need to refresh browser to see card

### ISSUE THREAD

**Issue by bschatzow** [amaximus/garbage-collection-card#13]
I have the following code for the card.
```
      - cards:
          - entity: sensor.garbage
            icon_color: brown
            icon_size: 35px
            type: 'custom:garbage-collection-card'
          - entity: sensor.garbage_2
            icon_color: brown
            icon_size: 35px
            type: 'custom:garbage-collection-card'
          - entity: sensor.recycle_2
            icon_color: brown
            icon_size: 35px
            type: 'custom:garbage-collection-card'
          - entity: sensor.branches_2
            icon_color: green
            icon_size: 35px
            type: 'custom:garbage-collection-card'
          - entity: sensor.yard_waste_2
            icon_color: green
            icon_size: 35px
            type: 'custom:garbage-collection-card'
        type: vertical-stack
'''
I can only see the card if I refresh the screen in chrome.  If I try edit the ui is blank.  I believe there is a conflict between this card and the vertical stack card.  This code did work several updates ago.  The custom garbage collection card does work by itself.

**Comment by amaximus** [comment]
This has nothing to do with the card itself, it's most probably caused by the fact that you are editing the Lovelace config in the browser. Browser cache settings might also to be suspected.

**Comment by bschatzow** [comment]
It only does it with the card inside the vertical stack. No problem with the vertical stack and no problem with the custom garbage cards by themselves.  Only when card is used inside.

**Comment by bschatzow** [comment]
After the update to hassio .103 my problem is resolved.  Not sure what the issue was, maybe my yaml formatting as the update would not take it as I originally had it.

**Comment by amaximus** [comment]
Sorry for the late answer.
As I said, the card itself displays within a standard HA div, therefore alignment with other elements (e.g. vertical stack) is handled by Lovelace itself.
