### ISSUE TITLE
(Request) Modify text size

### ISSUE THREAD

**Issue by jankete** [amaximus/garbage-collection-card#17]
Would it be possible to get an option to change the text size as we can do for the icon (with icon_size)?

**Comment by jankete** [comment]
Alternatively you could the CSS variables which can be modified via card-mod.

**Comment by amaximus** [comment]
Newest release adds support for font size for friendly_name and details.

Please check and get back to me with results.

**Comment by jankete** [comment]
I was now able to test, an it workes. Thanks!
