### ISSUE TITLE
sensor translation files omitted

### ISSUE THREAD

**Issue by lseufer** [amaximus/garbage-collection-card#18]
Apparently the card doesn't load the sensor.XX.json file and only use the English version. Everything in the XX.son is translated but not the sensor one.

**Comment by amaximus** [comment]
Please note that you reported to the wrong project as the sensor is provided by the Garbage Collection custom component [1].
The Lovelace custom card garbage-collection-card relies on the stat and attributes provided the aforemention custom component.

[1] https://github.com/bruxy70/Garbage-Collection

**Comment by jankete** [comment]
Hi,
I think it's related to the card and not the sensor. 

Example for showing the same sensor via glance card:
![image](https://user-images.githubusercontent.com/22338766/72500390-a3748a00-3834-11ea-8c72-21e1a6703c31.png)

an via your card:
![image](https://user-images.githubusercontent.com/22338766/72500406-aa9b9800-3834-11ea-9d84-07cef648ed86.png)

As you can see the text is translated on glance card by home assistant using the "sensor.DE.json" here. The garbage-collection-card doesn't seem use this and shows english only.

maybo @bruxy70 can tell something about it as there is a relatet issue here: https://github.com/bruxy70/Garbage-Collection/issues/66

**Comment by bruxy70** [comment]
All I can say is, that the sensor does the translation to German, as demonstrated on the glance card.
The way Home Assistant works is the following:
* Let's assume you have 3 users, one has configured his language as English, second as German, third as French.
* The sensor state will be `tomorrow` (all lowercase) - for all users, regardless of the language configured on the user profile. I guess that makes sense - if the actual sensor state would depend on selected language, then all the automations etc. would stop working when you change the language...
* Using the translation service (configured in sensor.XX.json), the front end will show the status for the users following way:
  * English user: `Tomorrow`
  * Geman user: `Morgen`
  * French user: `Demain`

The sensor works on the backend, the backend does not have access to the translation services. So even if I wanted to hard-code the translation to one language for all users, I cannot do that. The translation is done by the front end based on the language configured on the user profile.

I do not know why or how the glance does render the translated value and the custom card does not.

**Comment by amaximus** [comment]
The text for next date (today, tomorrow or a date with all the translations) is handled by the custom component. The custom card takes these attributes and displays them.
It would worth checking that even your browser is set to e.g. German, the sensor still has attributes in English. These are taken over by the custom card.
It seems that I need to do some extra reading on frontend translation services.

**Comment by jankete** [comment]
The browser is for sure set to German as other cards and the whole UI is shown in German where translations are available.

**Comment by amaximus** [comment]
@jankete I reproduced the issue. Please see below my findings.

You didn't mention, but you must have defined the Restmüll sensor with verbose_state=yes that will set the state of the sensor to 'today' or 'tomorrow' (instead of 0-2 values) "on those days" :)  regardless of the browser language.
The custom card only takes whatever string finds as state of the sensor and displays it.

@bruxy70  since the translation is done in the custom component, I'd propose to have the state of the sensor set to the translated string in case of today and tomorrow when verbose_state=yes and there is no verbose_format set (thus using the default).

**Comment by bruxy70** [comment]
@amaximus , That won't work.
The language is configured in the user profile settings. The integration works on the backend, it sets the status even if there is no user logged in. And there is single status for the sensor, it cannot have multiple values if there are multiple users with different languages.
The front end has to display the value based on the selected language, and this is done by the plugins. The integration does not control how is the state displayed. 
If you read the design guidelines, it is supposed to work the way I did that.
If I ignored the guidelines and wanted to ignore the language set in the user profile and have a language as a parameter, that won't work either, as the translation is not available for integrations. 
So I suppose the question is, how to use the polymer to process the state the same way the other cards do. I have no clue.

**Comment by bruxy70** [comment]
BTW, if you wanted to replicate that. Configure the sensor the way you did, and set language to German for example. Then you go to the Developer Tools/Sates and search for the sensor. It will show the actual state value. Then you click to the (i) icon, and it will display the sensor state the same way as the Lovelace cards do....
Have you ever wondered why the sensors show lowercase state in the Developer tools and then with first capital letter in Lovelace? This is why. The value is supposed to be all lowercase (e.g. on/off). Then there is a translation file (even for English) that displays that as (On/Off).

**Comment by amaximus** [comment]
@bruxy70 , you are right and I know there should be a translation done on front-end as well. I don't want to re-invent the wheel by applying some custom translation mechanism, but could not find any documentation or examples on translating custom cards. So I guess I still have to do some translation in the custom card.

**Comment by amaximus** [comment]
I've been looking at the translation mechanism this morning and I will probably make use of the translation file of the your custom component.

**Comment by bruxy70** [comment]
Are you on Discord? I'd ask the folks there. I got a lot of help from people like Ludeus (HACS), Thomasloven (he is great with front end) or even balloob (Paul)

**Comment by amaximus** [comment]
No, i'm not on Discord. I created a topic on the community forum, but got no answer yet.

**Comment by bruxy70** [comment]
Does this help? https://github.com/home-assistant/home-assistant-polymer/blob/8b659498b64bb925ad976cf3200a30644670d78e/src/panels/lovelace/cards/hui-glance-card.ts#L186

**Comment by amaximus** [comment]
Thanks for your help. I will have a look at it.

**Comment by amaximus** [comment]
@jankete , @bruxy70 , @lseufer newer version of the card supports translation.

Please check and let me know the results.

**Comment by jankete** [comment]
Unfortunately it's still showing everything in English. Regardless if I use verbose on the sensor or not.

**Comment by amaximus** [comment]
@jankete do you install it via HACS? The path to the translations is set for HACS install.

**Comment by jankete** [comment]
Yes I did an update from 1.1 to 1.2 via HACS.

**Comment by amaximus** [comment]
The translations directory was missing from the release package.
Will publish a new release soon.

**Comment by amaximus** [comment]
Please remove the installation through HACS and reinstall it (version 1.2.2).

**Comment by jankete** [comment]
Now I get "undefined".

![Screenshot_20200118-080233](https://user-images.githubusercontent.com/22338766/72660086-0bf47000-39c9-11ea-8466-0af827997e5f.png)

**Comment by amaximus** [comment]
@jankete , fixed the condition that caused undefined to be displayed.

Please update, check and confirm.

**Comment by jankete** [comment]
Sorry for the delay. The "tomorrows" state seems to work now:

![image](https://user-images.githubusercontent.com/22338766/72867697-158b1a00-3ce0-11ea-923e-7572eb498900.png)

Let's wait until tomorrow. If the "today" state is fine too, we could close here :-)

**Comment by jankete** [comment]
Even "Today" is fine now. 

![image](https://user-images.githubusercontent.com/22338766/72966212-9caebf80-3dbe-11ea-8ed0-dcc89dd43d32.png)

So I think we can close here.
