### ISSUE TITLE
FR - Customizable options

### ISSUE THREAD

**Issue by SeLLeRoNe** [amaximus/garbage-collection-card#2]
Hi,
it would be able to have some additional options as per:
- Ability to hide the date and the count
- Ability to have all the sensors in a single card with the option to show only what it is due in the next 24h hours
- Ability for the text to follow the UI language instead of showing always English (not big deal for me, but I am implementing this for my father and he doesn't speak englihs :) )
- Ability to set a friendly name on each entity (this might be might be more for the integration itself rather then the card, but it might also be applied on both

I hope someone else will find those useful :)

Thanks for your work
Andrea

**Comment by amaximus** [comment]
Hi,

added support for:
* icon color for due date (including the day before)
* hide date
* hide days
* translation support with fallback on English words

(!) Note: date specification is very different in different languages and Home Assistant doesn't have dedicated strings for words like 'on' or 'in' that are used in date specification. Therefore don't
expect much from this.

**Comment by amaximus** [comment]
Please also note that the owner of the Garbage Collection custom component added icon support recently, so you may now define different icons for the different sensors of this platform.

**Comment by SeLLeRoNe** [comment]
Thank you very much :)

Yep I did notice the support for different icon on the component itself :)

**Comment by amaximus** [comment]
As for option 2:
you may use an entities card and list the custom cards as entities. It's not exactly what you wanted, but sort of.
Also you may use conditional card to show the garbage collection card on condition of the sensor state not being equal to 2.

As for option 4: this is covered by the garbage_collection platform's name parameter.

**Comment by SeLLeRoNe** [comment]
Hi,
following what my father preferred to have as a visual "feedback" from those information, I had to switch to an entity card using the secondary-info custom-card to show what is due and automation to change the status value to some pre-defined text (in Italian).

So, right now, my experiment (which my father is happy with, considering there is not much more I can do to customize it) is this:
![image](https://user-images.githubusercontent.com/9599441/64924167-d143b680-d7e1-11e9-8073-8f0015e80f74.png)

And this is the code (in case someone want to replicate this):
```
      - type: vertical-stack
        cards:
          - type: custom:hui-entities-card
            show_header_toggle: false
            entities:
              - entity: sensor.spazzatura_umido
                icon: mdi:trash-can
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "Lun - Gio - Sab [[ if(sensor.umido.attributes.days == 1, '<b style='color:orange'>#</b>' , if(sensor.umido.attributes.days == 0, '<b style='color:red'>#</b>', '<b style='color:blue'>#</b>')) ]]"
                style: |
                  :host {
                    --paper-item-icon-color:
                        rgb(153, 102, 0);
                  }
              - entity: sensor.spazzatura_secco
                icon: mdi:trash-can
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "Sab [[ if(sensor.secco_non_riciclabile.attributes.days == 1, '<b style='color:orange'>#</b>' , if(sensor.secco_non_riciclabile.attributes.days == 0, '<b style='color:red'>#</b>', '<b style='color:blue'>#</b>')) ]]"
                style: |
                  :host {
                    --paper-item-icon-color:
                        rgb(115, 115, 115);
                  }
              - entity: sensor.spazzatura_carta
                icon: mdi:trash-can
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "Mer [[ if(sensor.carta_e_cartone.attributes.days == 1, '<b style='color:orange'>#</b>' , if(sensor.carta_e_cartone.attributes.days == 0, '<b style='color:red'>#</b>', '<b style='color:blue'>#</b>')) ]]"
                style: |
                  :host {
                    --paper-item-icon-color:
                        rgb(0, 0, 255);
                  }
              - entity: sensor.spazzatura_vetro
                icon: mdi:trash-can
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "Ven [[ if(sensor.vetro_e_metalli.attributes.days == 1, '<b style='color:orange'>#</b>' , if(sensor.vetro_e_metalli.attributes.days == 0, '<b style='color:red'>#</b>', '<b style='color:blue'>#</b>')) ]]"
                style: |
                  :host {
                    --paper-item-icon-color:
                        rgb(51, 204, 51);
                  }
              - entity: sensor.spazzatura_plastica
                icon: mdi:trash-can
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "Mar [[ if(sensor.plastica.attributes.days == 1, '<b style='color:orange'>#</b>' , if(sensor.plastica.attributes.days == 0, '<b style='color:red'>#</b>', '<b style='color:blue'>#</b>')) ]]"
                style: |
                  :host {
                    --paper-item-icon-color:
                        rgb(255, 255, 0);
                  }
```

Thanks again for your time, and feel free to take inspiration from my outcome if you want :)

Also, side note, what my father prefer was to have all the icon (as per text) alligned to the left as a norma entity card.
Another thing you might notice, is the "#" char that become red on "today", yellow on "tomorrow" and blue on any other day ;)

Might be worth to have the same feature on your card maybe ;)

Thanks again
Andrea

**Comment by amaximus** [comment]
Thanks for sharing this, looks great.
