### ISSUE TITLE
Custom element doesn't exist: garbage-collection-card.

### ISSUE THREAD

**Issue by tpsailer** [amaximus/garbage-collection-card#21]
Version: 1.2.3
Installed from HACS, allowed interface to add resource entry to lovelace config.
Restarted hass for good measure.

Can not find custom element. 
Resource added was: url: /community_plugin/garbage-collection-card/garbage-collection-card.js

There may be a few things wrong...
1) was installed into www/community/garbage-collection-card
2) I think should be referenced as /local/community/garbage-collection-card/garbage-collection-card.js

Changing url manually and restarting does not solve the issue.

**Comment by amaximus** [comment]
Could you please clear you browser's cache and reliad the page?

**Comment by tpsailer** [comment]
I just reinstalled it.

What should the URL be for the resource? By default, it doesn't work.

**Comment by amaximus** [comment]
The URL should be what you referred to as point 2. However I don't use the interface approach, but editing directly the yaml files.

**Comment by tpsailer** [comment]
I'm installing it via HACS, and if I change the resource, HACS thinks the installation is screwed up.
And it doesn't work.

resources:
  - type: module
    url: /local/community/garbage-collection-card/garbage-collection-card.js


From the card:

entity: sensor.richland_pickup
hide_date: true
icon_color: green
icon_size: 35px
type: 'custom:garbage-collection-card'



Custom element doesn't exist: garbage-collection-card.
entity: sensor.richland_pickup
hide_date: true
icon_color: green
icon_size: 35px
type: 'custom:garbage-collection-card'

**Comment by amaximus** [comment]
Try to put the type line before the entity.

**Comment by tpsailer** [comment]
- type: 'custom:garbage-collection-card'
         entity: sensor.basin_disposal


Custom element doesn't exist: garbage-collection-card.
type: 'custom:garbage-collection-card'
entity: sensor.basin_disposal

**Comment by tpsailer** [comment]
Needs Chrome > 74.x to work...
