### ISSUE TITLE
Implement the use of custom icons (.jpg)

### ISSUE THREAD

**Issue by SuperNeo84** [amaximus/garbage-collection-card#26]
It can possible, to implement the use of custom icon (for eg. a .jpg file )?

**Comment by amaximus** [comment]
The card takes the icon information from the custom component. The custom component allows customizing the icons, however the de facto icons are Material Design Icons (mdi:something).
You may try however to specify a local path like "/local/your_img.png". Be aware of rules on local images (size, transparency, etc.).
