### ISSUE TITLE
Card no longer working in 0.107

### ISSUE THREAD

**Issue by codypet** [amaximus/garbage-collection-card#29]
Upgraded to 0.107 and now the card shows this error:
![image](https://user-images.githubusercontent.com/17790157/76987449-8eda6e00-6919-11ea-8570-eacca5777651.png)
Almost all my other Lovelace cards needed to be reloaded with the upgrade, but this one didn't come back.

I tried 
`  - type: module
    url: /www/community/garbage-collection-card/garbage-collection-card.js`
`  - type: module
    url: /community-plugin/garbage-collection-card/garbage-collection-card.js`
And neither worked.

**Comment by amaximus** [comment]
Just updated my instance to 0.107.0 and the following line works:
```
  - {type: js, url: '/local/community/garbage-collection-card/garbage-collection-card.js'}
```

**Comment by codypet** [comment]
Yep!  Thank you kindly!
