### ISSUE TITLE
Different icon color standard/due date not working (1.5.4 / 108.9)

### ISSUE THREAD

**Issue by Liese2007** [amaximus/garbage-collection-card#33]
Hi,
with my code
```
type: 'custom:garbage-collection-card'
entity: sensor.stadtreinigung_hamburg_xxxx_gelbe_wertstofftonne_sack
icon_size: 35px
icon_color: yellow
hide_date: true
```
The Card works fine in Manual Card of Lovelace.
But all icons are red.
![Screenshot-Garbage-Card](https://user-images.githubusercontent.com/55997073/80490585-df55da00-8961-11ea-8abd-991a283a22bf.JPG)

I installed via HACS.
Resources are set in Lovelace Dashboard (with Resources Tab shown).
I hope I have not missed a setting...

Regards
Jörg

Amendment:
These are the attributes shown in Developer Tools:
```
Last update: '2020-04-28T15:04:44.914633'
unit_of_measurement: ''
friendly_name: Biotonne
icon: 'mdi:trash-can-outline'
device_class: timestamp
```

**Comment by amaximus** [comment]
I wonder what provides the sensor's state value and attributes as the Garbage Collection platform (https://github.com/bruxy70/Garbage-Collection/) doesn't set device_class and unit_of_measurment.

My test sensor with card config set to similar values shows up in yellow:

```
(ha_venv3_7) pi@raspberrypi:~/homeassistant_conf $tail -5  ui-lovelace.yaml
      - type: custom:garbage-collection-card
        entity: sensor.test_garbage_weekly
        icon_color: yellow
        icon_size: 35px
        hide_date: true
(ha_venv3_7) pi@raspberrypi:~/homeassistant_conf $
```
![screenshot-2020 04 28-20_44_03](https://user-images.githubusercontent.com/2511168/80525173-18597300-8991-11ea-82f2-e601d2341624.png)

**Comment by amaximus** [comment]
Moreover please check the state value of sensor..stadtreinigung_hamburg_xxxx_gelbe_wertstofftonne_sack. According to the dates it should be 2, while the colors indicate 1 or 0.

**Comment by Liese2007** [comment]
The state of the sensors is a timestamp like:
`2020-05-06T00:00:00` for Biotonne

**Comment by amaximus** [comment]
The custom card was written to process state and attributes from Garbage Collection platform ((https://github.com/bruxy70/Garbage-Collection/), so it expects attributes like next_date and days [till the collection]. Your sensor doesn't seem to have these.

**Comment by amaximus** [comment]
Any update on this issue? 
Is the sensor provided by Garbage Collection custom platform?

**Comment by Liese2007** [comment]
Sorry, 
my mistake.
You are right, that my waste disposal provider has different interface not in line with your component.

Thanks for your effort.
Greetz
