### ISSUE TITLE
Log error in .109 update

### ISSUE THREAD

**Issue by bschatzow** [amaximus/garbage-collection-card#34]
garbage_collection: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

**Comment by nighthawk321** [comment]
I fixed this by going into the file system of HA via configurator, go to custom_components then go into the garbage_collection folder. You will see '.translations', click rename and then simply delete the dot in front of translations.

**Comment by amaximus** [comment]
Please note that you've reported the issue to the wrong place: the related custom_component is handled by https://github.com/bruxy70/Garbage-Collection/ .
The card uses its own solution for translations, thus not affected by the changes in 0.109.0.
