### ISSUE TITLE
Icons dissapeared after updating to 0.110

### ISSUE THREAD

**Issue by scottamha** [amaximus/garbage-collection-card#36]
After updating to 0.110 the icons have disappeared on my lovelace cards.

**Comment by HarrisonPace** [comment]
+1

**Comment by BartEngelen** [comment]
+1

**Comment by amaximus** [comment]
Newest version (1.5.5) fixes the disappeared icons issue.
Please upgrade, flush the broswer cache and reload the page.

Please get back to me with results.

**Comment by BartEngelen** [comment]
Hello,
The icons are back, thanks !
But now it seems that the icon_size doesn't work
Regards,
Bart

**Comment by aptonline** [comment]
Yeah I'm seeing the same issue, icons size is not being respected in 0.110.0 and 1.5.5.

![Screenshot 2020-05-21 at 11 52 41](https://user-images.githubusercontent.com/190136/82552297-b6d49080-9b59-11ea-9d11-a15c6e111842.png)

**Comment by caddyblack** [comment]
Still no icon even after 1.5.5. install.
`cards:
  - entity: sensor.plastic
    hide_before: 7
    hide_date: false
    icon_color: grey
    icon_size: 35px
    type: 'custom:garbage-collection-card'
  - entity: sensor.papier
    hide_before: 7
    hide_date: false
    icon_color: grey
    icon_size: 35px
    type: 'custom:garbage-collection-card'
  - entity: sensor.groenbak
    hide_before: 7
    hide_date: false
    icon_color: grey
    icon_size: 35px
    type: 'custom:garbage-collection-card'
  - entity: sensor.groenbak_extra
    hide_before: 7
    hide_date: false
    icon_color: grey
    icon_size: 35px
    type: 'custom:garbage-collection-card'
  - entity: sensor.grijsbak
    hide_before: 7
    hide_date: false
    icon_color: grey
    icon_size: 35px
    type: 'custom:garbage-collection-card'
type: `vertical-stack`

![image](https://user-images.githubusercontent.com/48408773/82564146-8ea85a00-9b78-11ea-81b4-7f014c14d621.png)

![image](https://user-images.githubusercontent.com/48408773/82564252-c0b9bc00-9b78-11ea-823e-a1549fada4c7.png)

Can you check what can be wrong? 
I found no clue in the system log

**Comment by amaximus** [comment]
@caddyblack could you please flush your browser cache and reload the page?

**Comment by caddyblack** [comment]
That was the trick.
I did a re-load of the page but that is not clearing the cache (I should have known that).
A separate clear cache command did the job. Icon is back again.
Thank you for solving the issue so fast after the new 110 release.

![image](https://user-images.githubusercontent.com/48408773/82568646-6bcd7400-9b7f-11ea-9a68-a6c2a4aafa02.png)

**Comment by HarrisonPace** [comment]
Works for me after clearing cache 👍

**Comment by amaximus** [comment]
@BartEngelen , @aptonline pushed a new release (1.5.6) that fixes the icon size issue.

Please upgrade and get back to me with results.

**Comment by aptonline** [comment]
@amaximus Fixed for me, thanks 👍

**Comment by BartEngelen** [comment]
@amaximus works for me also thanks !
