### ISSUE TITLE
Icons randomly flicker

### ISSUE THREAD

**Issue by Woodcat64** [amaximus/garbage-collection-card#37]
This happens in HA .110 and later, Firefox (Windows 10, Linux and Android). 
No flicker in Chrome or Official Android app

**Comment by amaximus** [comment]
The card uses standard ha-icon object with svg icons from Material Design Icons set. It doesn't do anything else apart from displaying it with a custom color and size.
I presume this is more like a browser related issue.

**Comment by Woodcat64** [comment]
You most likely right. Strange thing is that there is no MDI icons flicker in other lovelace cards.  I will wait to see if FF or HA update will fix this.
Thanks
ps. Just adding error form FF developer tool

InvalidStateError: XMLHttpRequest has an invalid context.
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
