### ISSUE TITLE
(Request) Text alignment

### ISSUE THREAD

**Issue by Woodcat64** [amaximus/garbage-collection-card#4]
Currently it seems text centre align by default, making cards uneven when they are above each other.
It would look better if text and the icon could be align left. 
![garbage](https://user-images.githubusercontent.com/50119854/64568743-87625880-d329-11e9-9056-1642921941a5.PNG)

**Comment by amaximus** [comment]
Thanks, that makes sense.

I'll make the modifications soon.

**Comment by amaximus** [comment]
Fixed. Please check and get back to me with results.

Thanks.

**Comment by Woodcat64** [comment]
Fixed. Looks great.
Thank you
![Capture1](https://user-images.githubusercontent.com/50119854/64652230-56e5f180-d3f1-11e9-8bb1-b902fc2b130e.PNG)
