### ISSUE TITLE
Missing translation file

### ISSUE THREAD

**Issue by grewhit25** [amaximus/garbage-collection-card#40]
Thanks for this great app I find it extremely useful. 
I am seeing the entry below in the my Home Assistant logs continuously. The translation file is clearly not at the location referenced, but there is a file en.json there.

My question is; is this a bug or have I missed a configuration step?

I am on the latest version installed via HACS.

```logs
[29/Jul/2020:20:51:18 +0000] "GET /local/community/garbage-collection-card/en-GB.json HTTP/2.0" 404 14
```

**Comment by amaximus** [comment]
Thanks for reporting this bug.
Fixed it in the newest release of the card. Please update the card and get back to me with results.

**Comment by grewhit25** [comment]
Thanks for your response and quick fix.
I've updated to the latest release and the issue have been resolved.

Thanks again. 
Closing.

**Comment by joselito11** [comment]
@amaximus Please add Slovenian language:
```Logger: custom_components.hacs.web.category
Source: custom_components/hacs/webresponses/category.py:31 
Integration: HACS (documentation, issues) 
First occurred: 20:07:00 (56 occurrences) 
Last logged: 20:54:47

Tried to serve up '/config/www/community/garbage-collection-card/sl.json' but it does not exist

Example:

{
    "state": {
        "today": "danes",
        "tomorrow": "jutri",
        "Today": "Danes",
        "Tomorrow": "Jutri"
    },
    "other": {
      "due": "zapadlost",
      "Due": "Zapadlost",
      "due_today_order": "false"
    }
}

```

**Comment by amaximus** [comment]
Thanks for the Slovenian translation. It has been added in the 1.11.0 version. Please update the card.

**Comment by joselito11** [comment]
Thank you!
