### ISSUE TITLE
Add option to click on sensor to collect garbage.

### ISSUE THREAD

**Issue by Adam-North** [amaximus/garbage-collection-card#41]
The garbage collection integration recently came out with a service garbage_collection.collect_garbage. I'd like to be able click on the card to hide it until my next hide_before day.

**Comment by amaximus** [comment]
Thanks for the heads-up on the new service for garbage_collector.
The solution is ready and it's being tested right now.
I'll get back to you once it's released.

**Comment by amaximus** [comment]
Newest release (1.7.0) adds  support for hiding the card by clicking the icon when garbage was prepared or collected.

Please update the card and get back to me with results.

**Comment by Ndrinta** [comment]
I've put back the original card and I'll give it a go.
Happy to report if I'll encounter any bugs 😁

**Comment by Adam-North** [comment]
I've updated the card and I'll wait for trash day on Friday.

**Comment by Adam-North** [comment]
Seems to have worked correctly for me

**Comment by amaximus** [comment]
Great, thanks for testing.
