### ISSUE TITLE
No longer working in version .115

### ISSUE THREAD

**Issue by mattclair** [amaximus/garbage-collection-card#42]
After installing 0.115 the garbage-collection integration is no longer working. The error from the log is below.

Setup failed for garbage_collection: Requirements for garbage_collection not found: ['typing'].

**Comment by amaximus** [comment]
This is an issue with the custom integration. You can try manually install typing python module and restart HA. If that doesn't solve the issue, you should open an issue on the custom integration (not the caed) that was created and maintained by bruxy70.

**Comment by mattclair** [comment]
My bad.  Didn't realize this was the card and not the integration.  Thanks for pointing me in the correct direction.
