### ISSUE TITLE
Icon color doesn't work all the time

### ISSUE THREAD

**Issue by bschatzow** [amaximus/garbage-collection-card#43]
I have four different garbage sensors and set the color via
 icon_color: blue 
for example on my recycle. Sometimes it shows as blue sometimes brown.  
Am I missing something?

**Comment by amaximus** [comment]
When the garbage collection is due today or tomorrow, the color is changed as per parameters due_color and due_1_color that default to red.
Did you manage to find a pattern when they change color?

**Comment by bschatzow** [comment]
That is what it is doing. I need to read the docs better.  Thanks
