### ISSUE TITLE
Not working with new version 0.116?

### ISSUE THREAD

**Issue by alfiro** [amaximus/garbage-collection-card#48]
Card was perfectly working on version 0.115 and after update to  0.116 I'm gettng this error:
Can you tell me how to solve it?
![2020-10-08_13h04_31](https://user-images.githubusercontent.com/9274097/95516112-be6fc700-098c-11eb-8a97-1e1e207825cd.jpg)

Thank you so much for your support.

**Comment by amaximus** [comment]
Could you flush your browser's cache and shift-reload the page?

Please also make sure your configuration.yaml has the below entry for the card in the lovelace resources section:

```
lovelace:
  resources:
    - {type: js, url: '/hacsfiles/garbage-collection-card/garbage-collection-card.js'}
```

**Comment by Alloc186** [comment]
Hello, the same problem here...

![2020-10-10 (1)](https://user-images.githubusercontent.com/37019014/95661706-9cfc1000-0b31-11eb-81c5-cac88309bfd8.png)


![2020-10-10 (2)](https://user-images.githubusercontent.com/37019014/95661720-c5840a00-0b31-11eb-8c07-bcd1a79ac2d2.png)

**Comment by amaximus** [comment]
For Lovelace in yaml it works as expected. The setConfig is defined in the card, but it's invoked by Lovelace, so the error is generated on a higher level (and in UI mode).
I don't know how much work is to set it to yaml mode at least for the time of the tests.

**Comment by alfiro** [comment]
> Could you flush your browser's cache and shift-reload the page?
> 
> Please also make sure your configuration.yaml has the below entry for the card in the lovelace resources section:
> 
> ```
> lovelace:
>   resources:
>     - {type: js, url: '/hacsfiles/garbage-collection-card/garbage-collection-card.js'}
> ```

It works! Thank you so much for your support.
