### ISSUE TITLE
`hide_days = false` not working

### ISSUE THREAD

**Issue by lambtho12** [amaximus/garbage-collection-card#5]
If I put `hide_days = true` it works as expected.
If I put nothing, it show the days as expected by default.

However if I explicitly put `hide_days = false`, it still hide the days as if it was set to `true`. It is not a big deal as it can be fixed by removing the `hide_days` parameter altogether but it is a bit counterintuitive.

**Comment by amaximus** [comment]
Fixed the hide parameters logic.

Please check and get back to me with results.

**Comment by lambtho12** [comment]
Just checked. Everything works as expected. Thank your for the quick fix !
