### ISSUE TITLE
Can you add PL lang?

### ISSUE THREAD

**Issue by krzysiek2788** [amaximus/garbage-collection-card#50]
Hi,

Can you add pl.json below you can find what need to be inside this file:

{
    "state": {
        "today": "dziś",
        "tomorrow": "jutro",
        "Today": "Dziś",
        "Tomorrow": "Jutro"
    },
    "other": {
        "due": "termin",
        "Due": "termin",
        "due_today_order": "true"
    }
}

**Comment by amaximus** [comment]
Polish translation included in version 1.12.0

Please update the card and get back to me with results.

**Comment by krzysiek2788** [comment]
Thanks :) all looks god after today update (where you delete "in days" when it is today or tomorrow). Only thing which is wrong is when there is more days. it should be for example 'za 5 dni' instead of  "in 5 days" as you can see below.
![image](https://user-images.githubusercontent.com/61471407/95825426-1d3c9400-0d31-11eb-8caf-dd576c4d5a45.png)
Maybe you can connect this with speak up option (first page of configuration new sensor):
![image](https://user-images.githubusercontent.com/61471407/95825504-3fcead00-0d31-11eb-8fb6-f65f16e26472.png)
And when someone change it here, it will reflect in the card as well?

**Comment by amaximus** [comment]
Right. Added translation for that part in version 1.14.0 released just now.

Please update the card and get back to me with results.

**Comment by krzysiek2788** [comment]
All perfect:
![image](https://user-images.githubusercontent.com/61471407/96018062-173ad600-0e4b-11eb-8a55-a97e21c871b7.png)
I will close topic thx :)
