### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by Bluhme1** [amaximus/garbage-collection-card#51]
In Danish translation I still get "Tomorrow" and "Today" instead of the Danish words

**Comment by amaximus** [comment]
When setting the custom component sensor's verbose_state to true, the translation is not in effect as the text takes the string defined by the sensor (verbose_format).

While verbose_state is false, the translation works as shown in the attached image.
![garbage_da](https://user-images.githubusercontent.com/2511168/95777147-ee3d0880-0cc5-11eb-8ffc-006be07e82de.png)

**Comment by Bluhme1** [comment]
Great. I can see that that. In my card I now have "I morgen in 1 days". How do I remove the "in 1 days"

**Comment by amaximus** [comment]
Set hide_days: true  in the card.

**Comment by Bluhme1** [comment]
Thank you very much. Just another feature request when you find the time and find it relevant.
The number of days is important when there is some time before collecting but when it is tomorrow or today it is less relevant. So is it - perhaps - possible to have an option to hide_days only when you are in the "tomorrow / today" interval?

**Comment by amaximus** [comment]
Good point, thanks.
Implemented in version 0.13.0. Please update the card and get back to me with results.

**Comment by Bluhme1** [comment]
Works great. Thank you. A minor thing. The text “in xxx days” is not translated. Is that supposed to be like that?

**Comment by amaximus** [comment]
Right. Added translation for that part in version 1.14.0 released just now.

Please update the card and get back to me with results.

**Comment by Bluhme1** [comment]
Works perfectly. Thank you again. You are awesome (and very quick). I cannot see the need for any improvement for now - but if I get an idea (or two) I will let you know

**Comment by amaximus** [comment]
Thanks for the confirmation. I'm open for enhancements, s odo not hesitate to open new feature requests.
