### ISSUE TITLE
Icon color: use default theme colors

### ISSUE THREAD

**Issue by danielrheinbay** [amaximus/garbage-collection-card#54]
By default, icon_color is black and due_color is red. This does not work very well with alternating HA themes (e.g. HA's default bright theme during the day, HA's default dark theme at night)

May I suggest changing the default colors to the theme's colors?
* icon_color should default to var(--paper-item-icon-color)
* due_color shoud default to var(--paper-item-icon-active-color)

Users of custom themes would also benefit from that.

**Comment by amaximus** [comment]
Thanks for this improvement idea.
It has been implemented in version 1.15.0 released just now.

Please update your card and let me know the results.

**Comment by danielrheinbay** [comment]
Working beautifully. Thank you 👍
