### ISSUE TITLE
[BUG} Tried to serve up '/config/www/community/garbage-collection-card/hr.json' but it does not exist 

### ISSUE THREAD

**Issue by bebach8** [amaximus/garbage-collection-card#56]
It is looking for language translation that is non existent. Home assistant version 0.116

Logger: custom_components.hacs.web.category
Source: custom_components/hacs/webresponses/category.py:31
Integration: HACS (documentation, issues)
First occurred: 6:02:45 PM (3 occurrences)
Last logged: 6:02:45 PM
Tried to serve up '/config/www/community/garbage-collection-card/hr.json' but it does not exist 

** To reproduce just restart HASS. 

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.15.1
 - Browser: chrome, firefox, edge
 - Browser language: english

Temporary workaround: 
Manually make copy of en.json and rename it to hr.json every time after update.

**Comment by amaximus** [comment]
I fixed the translation defaulting to English if there is no translation file for the language set in the browser in recent release 1.15.2.

Please update the card and get back to me with results.
If you provide the translation to Croatian of the following words/phrases, I'll be happy to add Croatian translation as well:
today, tomorrow, due (like due in 2 days), due today, due in X days

**Comment by bebach8** [comment]
Thank you, it works as expected.

Below is Croatian translation, if you need anything else just ask.

{
    "state": {
        "today": "danas",
        "tomorrow": "sutra",
        "Today": "Danas",
        "Tomorrow": "Sutra"
    },
    "other": {
        "due": "dospijeva",
        "Due": "Dospijeva",
        "due_today_order": "true",
        "in_days": "za DAYS dana"
    }
}

**Comment by amaximus** [comment]
THanks for the translation.
I added it in 1.16.0 release.

Please update your card and get back to me with results.

**Comment by amaximus** [comment]
Any update on this issue in the new version?

**Comment by bebach8** [comment]
No issues for now. It is working as expected. Thank you for your effort. Tested also in 0.117.2
