### ISSUE TITLE
Lovelace card not working since 0.118 [BUG] 

### ISSUE THREAD

**Issue by sr-as2** [amaximus/garbage-collection-card#58]
**Describe the bug**
The lovelace card is not visible (no error on the frontend) since the last update 0.118.

**To Reproduce**
1. Update to 0.118
2. Clear browser cache

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.16.1

**Comment by amaximus** [comment]
Could you please provide more detail on the issue? Browser console error or warning messages would help a lot.

After upgrading mine to 0.118.0, cards still load without issues.
![garbage118_0](https://user-images.githubusercontent.com/2511168/99689508-5cc07380-2a87-11eb-9483-f8820f5e0b0b.png)

**Comment by sr-as2** [comment]
Your right, i need to bring some details.

When i launch the chrome console i can see this:

![image](https://user-images.githubusercontent.com/48023575/99700142-1709a800-2a93-11eb-816a-6a5b8de49f4f.png)

My lovelace card configuration:
```
      - type: 'custom:garbage-collection-card'
        entity: sensor.poubelles
        icon_size: 40px
        icon_color: green
        title_size: 15px
        due_1_color: red
        hide_date: true
```

This morning, when i clic on the garbage card, it disapear... There is no error on the frontend. I don't knwo what i'm doing wrong

**Comment by amaximus** [comment]
It's not a bug. It's a feature :) .

Version 1.7.0 introduced the feature of clicking the icon on a card when collection day is today or tomorrow, hides the card until the day after due date (or if hide_before is used then until X days before next due date).
Version 1.8.0 made clicking valid for the whole card (not only the icon).

This is also mentioned in the README file [3].

On the other hand the warning message in the browser console is harmless and should be discarded.

[1] https://github.com/amaximus/garbage-collection-card/releases/tag/1.7.0
[2] https://github.com/amaximus/garbage-collection-card/releases/tag/1.8.0
[3] https://github.com/amaximus/garbage-collection-card/blame/master/README.md#L44

**Comment by sr-as2** [comment]
Ha ok thanks, sorry for that!
