### ISSUE TITLE
'No card type configured' error

### ISSUE THREAD

**Issue by dzidzior** [amaximus/garbage-collection-card#59]
I added the card via HACS and it gives me the error: "No card type configured." when I try to add it to the dashboard.

The link to the .js file is added to resources in the Lovelace config panel. Any ideas what can be wrong?

**Comment by amaximus** [comment]
Have you restarted HA in order the resource be recognized?

**Comment by dzidzior** [comment]
> Have you restarted HA in order the resource be recognized?

yes. Multiple times :-(

**Comment by amaximus** [comment]
Please try also clearing your browser cache.
Please make sure you see the Garbage Collection sensor values under the Developer Tools->States

If the issue still persists please provide the following information:
* browser
* HA version and mode (yaml or UI)
* Garbage Collection Card version
* provide the related Garbage Collection card configuration from your ui-lovelace.yaml.

**Comment by dzidzior** [comment]
> * browser
Chrome on OC and Safari on iPad

> * HA version and mode (yaml or UI)
Home Assistant 0.118.3 - not sure what you mean by 'yaml or ui'

> * Garbage Collection Card version
3.10 -  installed via HACS

> * provide the related Garbage Collection card configuration from your ui-lovelace.yaml.
I don't run Lovelace off its own YAML - it's all integrated (default setting) - could that be an issue? the .js file is added in Resources.

**Comment by amaximus** [comment]
I'm not familiar with the UI mode, but the card does not support configuration flow so I don't know how can you configure it.
In yaml mode you have to add at least the entity to work on (the rest of parameters will use default values).

The current version of the card is 1.16.1 as per [1].
It would help a lot if you could provide me some error and/or warning messages from the browser's console log.

[1] https://github.com/amaximus/garbage-collection-card/releases/tag/1.16.1

**Comment by dzidzior** [comment]
I've changed my Lovelace setup and reviewed the installation from the beginning. It started to work properly. Thank You for your help.

**Comment by amaximus** [comment]
Thanks for confimring.
