### ISSUE TITLE
Card not working with latest version of Chrome

### ISSUE THREAD

**Issue by danielbrunt57** [amaximus/garbage-collection-card#62]
**Describe the bug**
See screenshots...

**To Reproduce**
Create new card or try and view existing one using latest version of Chrome

**Expected behavior**
It should display.

**Screenshots**
![image](https://user-images.githubusercontent.com/49846893/102415820-b1371000-3fad-11eb-83bf-5d74ae89e37c.png)

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.16.4
 - Browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
 - Browser language: en-ca

**Additional context**
![image](https://user-images.githubusercontent.com/49846893/102415869-c744d080-3fad-11eb-8995-55b316b77077.png)
![image](https://user-images.githubusercontent.com/49846893/102415931-e17eae80-3fad-11eb-8b8d-3a018edc49df.png)
![image](https://user-images.githubusercontent.com/49846893/102416015-fd825000-3fad-11eb-85a8-8e3e22b87296.png)

**Comment by amaximus** [comment]
The card does not support configuration via config flow. You'll have to edit yaml files for configuing the card.

**Comment by danielbrunt57** [comment]
But I **was** using yaml for the garbage collection integration.  The issue is that the sensors disappeared when I clicked on them but only in Chrome, not in Firefox.  I removed the yaml config for the integration and added the sensors via config flow as a troubleshooting step and they are still working fine in Firefox (both visible) but still invisible in Chrome despite yesterday being garbage collection day.  I should at least be (re)seeing the garbage sensor in Chrome based on your post in the other thread...

**Comment by danielbrunt57** [comment]
Garbage collection finally decided to re-appear in Chrome...
![image](https://user-images.githubusercontent.com/49846893/102588706-bd60c180-40c2-11eb-83b9-c7f22eee9ae2.png)

**Comment by danielbrunt57** [comment]
Do you want me to close this issue and only post to #46 or stop posting to #46 and only post here?

**Comment by amaximus** [comment]
Yes, you can close this one and let's continue on the other thread (#46), if there are still issues to handle.

**Comment by danielbrunt57** [comment]
See #46
