### ISSUE TITLE
iOS fails to load card

### ISSUE THREAD

**Issue by bertybassett** [amaximus/garbage-collection-card#64]
Got this in resources 

![Screenshot 2020-12-28 at 12 35 15](https://user-images.githubusercontent.com/5606175/103214779-4a005080-4909-11eb-9c37-2a6df31ee911.png)

Web browser shows the card fine however iOS app fails to load card

**Comment by didav81** [comment]
Got the same problem. Ok with browser or Android app but error with iOS app.

**Comment by bertybassett** [comment]
did nothing different and today it is working on iso
