### ISSUE TITLE
[BUG] Icon doesn't show up.

### ISSUE THREAD

**Issue by Jonasn97** [amaximus/garbage-collection-card#72]
**Describe the bug**
I used the https://github.com/mampfes/hacs_waste_collection_schedule
with the garbage collection card and I get the data and it's showing that my garbage is being collected in 6 days, but the icon is not showing.
If I click on the icon it is showing a circle in icon_color around it, but the icon is missing for some reason.
I believe the issue is related to the frontend and not to the integration, because it's just not showing. Hope you can help me out with it.

**Expected behavior**
I wan't to see any icon.
When I put an alternative icon for each type, it doesn't change anything.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47939597/105614410-a3a15100-5dc9-11eb-9111-817b5ebbdcfb.png)

Configuration:
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://geo.osnabrueck.de/osb-service/abfuhrkalender/?bezirk=9 
      customize:
        - type: "OSB Restmüll"
          alias: "Restmüll"
        - type: "OSB Altpapier"
          alias: "Altpapier"
        - type: "OSB Biomüll"
          alias: "Biomüll"
        - type: "OSB Gelber Sack"
          alias: "Gelbe Tonne"
  day_switch_time: "12:00"

sensor:
  - platform: waste_collection_schedule
      name: "Nächste Tonnen"
      details_format: upcoming
      value_template: '{{value.types|join(", ")}} in {{value.daysTo}} Tagen'

**Environment:**
 - Garbage Collection Card version: 1.18.0
 - Waste Collection Schedule version: c294831
 - Browser: tested on Firefox and Edge
 - Browser language: German
 - Home Assistant 2021.1.4
**Additional context**
I hope you can help me with it. Thanks.

**Comment by amaximus** [comment]
Please note that the Garbage Collection Card expects state and attributes as per [1].
I presume [2] does not comply with that, that's why it doesn't show any data from the sensor.

[1] https://github.com/bruxy70/Garbage-Collection/
[2] https://github.com/mampfes/hacs_waste_collection_schedule

**Comment by Jonasn97** [comment]
Thanks, for some reason I overread the part with creating an additional sensor for this card.
