### ISSUE TITLE
[FeatureRequest] hide_icon and hide_title

### ISSUE THREAD

**Issue by thermoscookies** [amaximus/garbage-collection-card#73]
I would like to request hide_icon and hide_title. I've tried setting icon_size and title_size to 0px, and it kind of works but it isn't as clean as hiding them would be.

hide_title would be good for just showing the icon on a card, and also I have a card where I only want to show them number of days until next...

Here's how mine looks that I would like to clean up:
![image](https://user-images.githubusercontent.com/22629136/105939585-5cf06880-600e-11eb-9004-a3d42e69c4ff.png)

Thank you for the wonderful add-on already!

**Comment by amaximus** [comment]
Newset release (1.19.0) adds support for hiding icon and/or title.

Please update the card and get back to me with results.

**Comment by thermoscookies** [comment]
It looks a lot better than it did! Thank you!
![image](https://user-images.githubusercontent.com/22629136/106053722-f9168000-609f-11eb-96c7-f4c0be4451be.png)
