### ISSUE TITLE
[BUG] HACS flags error and resource doesn't load

### ISSUE THREAD

**Issue by Sudo-Rob** [amaximus/garbage-collection-card#74]
**Describe the bug**

Integrated with HACS 1.10.1 along with Garbage Collection 3.15.
The card resource doesn't appear to be loading.
Everything seemed to be working properly until the recent update to core-2021.2.0.
The sensor entities look to be properly formed.
The issue could be related to [BUG] #65, but my instance had been working until the recent Core update.

**Expected behavior**
Display of two cards and no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/56487711/106949067-85592080-66fa-11eb-8082-9b4b9f7a3122.png)
![image](https://user-images.githubusercontent.com/56487711/106949153-9ace4a80-66fa-11eb-954b-d719d673d920.png)
![image](https://user-images.githubusercontent.com/56487711/106949953-b38b3000-66fb-11eb-8708-93de722b0623.png)
![image](https://user-images.githubusercontent.com/56487711/106950021-cd2c7780-66fb-11eb-8f94-6be05f929f51.png)

**Environment (please complete the following information):**
- Compliant Supervised installation of HA with Debian
> -  core-2021.2.0
> - supervisor-2021.01.7
> - Docker version 20.10.1
- garbage-collection-card version 1.19.0
- Garbage Collection version 3.15

**Additional context**

![image](https://user-images.githubusercontent.com/56487711/106954493-e20c0980-6701-11eb-8b75-cf3d8e4f4155.png)

Also tried:

![image](https://user-images.githubusercontent.com/56487711/106954033-2fd44200-6701-11eb-8ad2-4d937d83b6f4.png)

![image](https://user-images.githubusercontent.com/56487711/106954965-88f0a580-6702-11eb-8a7f-5b52f03c73b6.png)

**Comment by amaximus** [comment]
Please replace /local/community with /hacsfiles in the resource definition then restart HA to take effect. If the issue still persists please flush tour browser's cache.

**Comment by Sudo-Rob** [comment]
I had no such directory so I made one, uninstalled the card, made a /hacsfiles directory, and then reinstalled the card.  Then I see this:

![image](https://user-images.githubusercontent.com/56487711/106962415-1638f780-670d-11eb-9705-9c47e34eae9d.png)

Do you suggest I delete all vestiges of the prior installs?

**Comment by amaximus** [comment]
You don't have to create the directory as HACS will install under www/community/..., but don't bother with that, simply write /hacsfiles/... instead, the rest will be handled by HA. Of course you'll have to restart HA after changing the resource path.

**Comment by Sudo-Rob** [comment]
It's always been at www/community/ and it's still there.  HACS doesn't provide the ability to target a specific directory.  It seems to look for a prior installation.

Why doesn't the card integration find it there with the /local/ reference that used to work?  Should I change it to /config/www/, or should I just delete all the files and move it manually to /hacsfiles/?

**Comment by amaximus** [comment]
That's how HA handles it. Do not uninstall it, simply write /hacsfiles/garbage-collection-card/... in the resource definition then restart HA. The files will still be under www/community, hacsfiles is sort of "virtual path".

**Comment by Sudo-Rob** [comment]
OK.  That almost appears it might be working, but _HACS still thinks it's broken_.  It'll take a few days to know for sure.  

I still don't understand why it worked before and doesn't now.  Was there a breaking change I missed?  Why are the other integrations (e.g. Garbage Collection) working without the "virtual path"?  Where is this virtual path documented?

Do you think this can be some sort of synchronization problem with HACS?  

BTW, thanks with the help.

**Comment by amaximus** [comment]
Integrations like Garbage Collection are installed to a different location as they are custom platforms/components. Cards are sort of plugins for the frontend; installed via HACS they end up under www/community/....

**Comment by Sudo-Rob** [comment]
The integration is working again, but HACKS still thinks it's not.  I see status as "not loaded."  I'd be happy to gather any information you need to resolve the issue.

Thanks.

**Comment by Sudo-Rob** [comment]
FYI: With a bit of help from @ludeeus, I figured out the issue:

![image](https://user-images.githubusercontent.com/56487711/107100650-07bd0f80-67e3-11eb-95e1-e37a91c98c35.png)

**Comment by amaximus** [comment]
Thanks for pointing this out. I will update the Readme.
