### ISSUE TITLE
Glance Card Layout [FeatureRequest]

### ISSUE THREAD

**Issue by nathbullen** [amaximus/garbage-collection-card#75]
I love the customisability of the current card, but I feel like it takes up quite a bit of space on my dashboard with 3-4 bins stacked vertically. It would be awesome to be able to lay the bins out in a glance style card while retaining the functionality of your custom card!

**Comment by amaximus** [comment]
Thanks for the idea.
Not that I'm not willing to implement it, but it would require rewriting the 80% of the code while using horizontal-stack and button cards or even custom:button card [1] would allow you to achieve a glance-type look with a lot of flexibility eventually displaying all of your garbage collection dates in one row. The hide_before behaviour could be achieved including conditional card as well.

[1] https://github.com/custom-cards/button-card
