### ISSUE TITLE
[BUG] Eltűnik és nem tudom előhozni

### ISSUE THREAD

**Issue by Ecoplay600** [amaximus/garbage-collection-card#76]
Van 2 kuka amit ki kell ugye írnia egy fekete és sárga fedelű

A fekete tökéletesen működik, viszont a sárgát hogy létrehoztam a főoldalon rákattintottam és egyből eltűnt és azóta bárhogy hivatkozok rá nem jön elő viszont a calendárba látom.

**Comment by amaximus** [comment]
Ez nem bug hanem feature. Az aznapi és a másnapi kuka esetén alapból clickre eltűnik a kártya és majd újra megjelenik az utána való napon (mikor már az esedékességen túl van).
Lévén többeknek volt ez gond, egy adott verzióban bekerült a hide_on_click, de hogy az eredeti funkcionalitás megmaradjon, az alapértéke true.

**Comment by Ecoplay600** [comment]
De hiába írom be neki ezt, akkor sem jelenik meg újra

**Comment by Ecoplay600** [comment]
Illetve akkor sem, ha már nincsen 1 nap sem hátra, mert átírom hogy mikor vigyék a szemetet

**Comment by amaximus** [comment]
Mihelyt egyszer az egyikre rányomtál és eltűnik meg kell várnod amíg túljut a következő esedékességi napon, utána megjelenik és ha a hide_on_click false-ra van állítva, akkor már nem lehet rá klikkelni, azaz lehet, de nem nem tűnik majd el.
