### ISSUE TITLE
Language change

### ISSUE THREAD

**Issue by Ecoplay600** [amaximus/garbage-collection-card#77]
where can i change language?

**Comment by amaximus** [comment]
The language used by default is the browser's language.
You may override this by hass_lang_priority. This will display the card in the language set in HASS (if translation is available).

**Comment by Ecoplay600** [comment]
As I see the language is not hungarian like you said, but In my HA language is Hungary, where can I put hass_lang_priority ? to config.yaml ?

**Comment by amaximus** [comment]
You'll have to use hass_lang_priority in the card configuration if you want to have the language set in Home Assistant to take priority over browser's language.

**Comment by Ecoplay600** [comment]
But if I add this to my card config then the language, like the rubbis take out "tomorrow" is not changed to "holnap"

**Comment by amaximus** [comment]
You might need to clear the browser cache and reload the page.

**Comment by amaximus** [comment]
You might need to clear the browser cache and reload the page.

**Comment by amaximus** [comment]
Any update on this issue?

**Comment by Ecoplay600** [comment]
The problem not solved. I don't even know why, but you're addon is still english, and not Hungary. I do anytink from you're instructions.

**Comment by amaximus** [comment]
Please let me know the language your browser is set to. In Chrome you can find this at: Settings->Advanvced->Languages. Which one is the first in the list?

Please also provide the card's full configuration.

**Comment by Ecoplay600** [comment]
My browser language is Hungary

      - type: entities
        entities:
          - entity: sensor.fekete_kuka
          - entity: sensor.sarga_kuka
        title: Kuka szállítás

I delete the card, now i use this, can i translate it to hungary?

**Comment by amaximus** [comment]
Please note that you are using default entities card from Lovelace, not the custom garbage collection card.

Once the card is installed and added to the resources, the custom garbage collection card definition could be something like:

```
 - type: custom:garbage-collection-card
   entity: sensor.fekete_kuka
   icon_size: 35px
   icon_color: green
   hide_date: true
```

Please note that the custom garbage collection card does not support multiple sensors yet, so if you have two sensors (fekete_kuka, sarga_kuka) you should have two card definitions, one for each sensor.

**Comment by Ecoplay600** [comment]
okay, and where can I add the hass_lang_priority ?

**Comment by amaximus** [comment]
You could extend the the above card definition with the extra hass_lang_priority, like:

```
- type: custom:garbage-collection-card
  entity: sensor.fekete_kuka
  icon_size: 35px
  icon_color: green
  hide_date: true
  hass_lang_priority: true
```

**Comment by Ecoplay600** [comment]
It's not working, it still said tomorrow[
![Képkivágás](https://user-images.githubusercontent.com/80219372/110834529-f1044f80-829d-11eb-8881-835602631597.PNG)
](url)

Code:
type: 'custom:garbage-collection-card'
entity: sensor.sarga_kuka
icon_size: 35px
icon_color: green
hide_date: true
hass_lang_priority: true


Config:
  - name: "Sarga kuka"
    frequency: "every-n-weeks"
    collection_days:
    - fri
    period: 4
    offset: -21
    date_format: '%Y-%b-%d'
    verbose_format: "{date} ({days} nap)"
    verbose_state: True

**Comment by amaximus** [comment]
It's because you are using verbose_state: true for the sensor.
Of course if you set verbose_state to false you will loose the string provided by verbose_format. In exchange you'll let the card to format the displayed string and you can control it at the card. Now it's controlled at the sensor.

**Comment by amaximus** [comment]
The sensor doesn't have Hungarian translation as per [1]

[1] https://github.com/bruxy70/Garbage-Collection/tree/development/custom_components/garbage_collection/translations

**Comment by Ecoplay600** [comment]
hmm, it's strange as i remember I had before.

**Comment by Ecoplay600** [comment]
What if I change maybe the DE translate? how can I use the DE config?

**Comment by Ecoplay600** [comment]
I changed config on sensorEN.json but it's not changed in main page

**Comment by amaximus** [comment]
The custom card will bypass the string part if verbose_state is true.

Try to set Lovelace language to German.
The sensor's Readme doesn't details the translation part.

For your last note: you'll have to restart HASS.

**Comment by amaximus** [comment]
You may also create a sensorHU.json based on sensorEN.json.

**Comment by Ecoplay600** [comment]
I always restart HASS when I change somethink in config, but nothink happened :/

**Comment by Ecoplay600** [comment]
![Képkivágás](https://user-images.githubusercontent.com/80219372/110836638-8f91b000-82a0-11eb-90b2-b2df5a2c4abe.PNG)

**Comment by amaximus** [comment]
The garbage collection sensor's translation should be (if you modify the English related file (sensor.en.json)):

```
{
    "state": {
        "garbage_collection__schedule": {
            "today": "Ma",
            "tomorrow": "Holnap"
        }
    }
}
```

**Comment by Ecoplay600** [comment]
I change it to this, and nothink happened, just noting see under the title

**Comment by amaximus** [comment]
It was the ${HASS_CONF}/custom_components/garbage_collection/translations/sensor.en.json, right?
And you restarted HASS afterward?

**Comment by Ecoplay600** [comment]
Yes

**Comment by amaximus** [comment]
Can you copy here the content of sensor.en.json?

**Comment by Ecoplay600** [comment]
{
    "state": {
        "garbage_collection__schedule": {
            "today": "Ma",
            "tomorrow": "Holnap"
        }
    }
}

**Comment by amaximus** [comment]
And HASS is set to English, right?

**Comment by Ecoplay600** [comment]
no it's hungary then I need to create sensor.hu.json? to make it work?

**Comment by amaximus** [comment]
yes

**Comment by Ecoplay600** [comment]
still not working

**Comment by amaximus** [comment]
It's named sensor.hu.json, located in ${HASS_CONF}/custom_components/garbage_collection/translations/sensor.en.json, HASS restarted afterwards? HASS running in Hungarian? That should work.
You may try setting the browser to Hungarian as described earlier above.

**Comment by Ecoplay600** [comment]
very strange what this, it's okay for me, but very strange
![Képkivágás](https://user-images.githubusercontent.com/80219372/110839767-39267080-82a4-11eb-96e3-c0233c165a05.PNG)

**Comment by Ecoplay600** [comment]
that's okay for me

**Comment by amaximus** [comment]
The above changes (adding sensor.hu.json) solved displaying in the entities.

Since your are still using verbose_state true that will bypass the string formatting and translation when using the custom garbage collection card.

So the current behaviour is expected and normal.

**Comment by amaximus** [comment]
try to clear the browser's cache and reload the page.

**Comment by Ecoplay600** [comment]
Working, thank you :D

**Comment by amaximus** [comment]
Great.
