### ISSUE TITLE
When you tap on a card, it disappears and no obvious way to get it back

### ISSUE THREAD

**Issue by happy-chap** [amaximus/garbage-collection-card#78]
Hi, initially I did this by accident, but if you tap on a card, the card disappears and there is then no obvious way to get the card back.

Steps to recreate:

- setup up 2-3 custom garbage collection cards in Lovelace
- Tap on one of the cards in the Lovelace UI and the card disappears
- Tap in the position that the card was occupying and you cannot get it back
- Edit the cards and save, and still the card does not come back

I assume what is happening is that when you tap on a card, it should switch to the state history display for that entity (as many other entities do in Lovelace) but that isn’t happening or showing and instead, the card just vanishes.

HA Core: core-2021.3.2
Supervisor: supervisor-2021.03.4
Garbage-Collection Integration: 3.17
Garbage-Collection-Card FrontEnd: 1.19.0

**Comment by happy-chap** [comment]
Sorry, just worked out this is intended behaviour - just confused me.

However, I have now set the cards to

         hide_on_click: false 

and refreshed the interface but the cards are still not displaying.

**Comment by amaximus** [comment]
The card will re-appear once the due date passes.
Since you disabled hide_on_click, further clicks will not hide the card.

**Comment by happy-chap** [comment]
Thanks. Just wonder if hide_on_click should default to false to avoid any confusion.

**Comment by amaximus** [comment]
When the feature request came in to hide the card on click (e.g. when garbage was prepared to be picked up), the solution was implemented without the possibility to switch this functionality off. Later, when using this funtionality was made optional controlled by the hide_on_click, to have backward compatibility and not break the current behaviour, the new configuration parameter was set to true by default.
