### ISSUE TITLE
Cannot read property 'setConfig' of undefined

### ISSUE THREAD

**Issue by compujunk** [amaximus/garbage-collection-card#8]
this is my config:

cards:
  - type: 'custom:garbage-collection-card'
    entity: sensor.gft_afval_groen
    icon_color: green
    hide_before: 2
  - type: 'custom:garbage-collection-card'
    entity: sensor.pmd_afval_plastic
    hide_before: 2
    icon_color: yellow
  - type: 'custom:garbage-collection-card'
    entity: sensor.restafval_grijs
    hide_before: 2
    icon_color: gray
  - type: 'custom:garbage-collection-card'
    entity: sensor.papier_blauw
    hide_before: 2
    icon_color: blue

But i get de error:  Cannot read property 'setConfig' of undefined
What can i do to solve this error

**Comment by amaximus** [comment]
Please make sure you have the module defined at the begining of the ui-lovelace.yaml (depending on your method of installation: HACS or manual).
Does any of your garbage collection cards appear on the UI or all four are missing?
Please make sure the sensors you are refering to exist.
Try to remove the quotes from one of the custom card definition, so it should look like:  type: custom:garbage-collection-card .

**Comment by compujunk** [comment]
I have it done with HACS and yes i have the module defined at the begining of the ui-lovelace.yaml
and yes all 4 are missing with this plugin.

the sensors themselves just work in hassio

I had already removed the quotes, but as soon as I write the card away, hassio adds it again

**Comment by amaximus** [comment]
What version of home-assistant are you using? Does cleaning the browser cache and reloading Lovelace UI produce the same error? Did it work before? Have you done any recent hassio upgrade?

**Comment by compujunk** [comment]
I use Home Assistant 0.99.3.
I emptied the browser cash from chrome and I also tried it in opera but that gives the same error message.
No, I am installing it for the first time so it has not worked before. 
I saw that there is now a new version 0.100.2 of hassio but I have not yet upgraded it

**Comment by amaximus** [comment]
Earlier version of 0.99.3 should be fine, however it was tested in Home Assistant, not hassio.
Could you please provide the resources type part related to this custom card? Does it use js or module type. I'd try the other one as well (so if you have type: js try with type: module).
I suspect something related to the differences between HomeAssistant and hassio.

**Comment by amaximus** [comment]
You may also check that you use latest javascript in the configuration.yaml.

**Comment by compujunk** [comment]
it uses module and I tried it with js but that also gives the same error message.
I also tried specifying the path where the scripts are stored, so: /local/community/garbage-collection-card/garbage-collection-card.js
but that also helped nothing

my configuration.yaml contains javascript_version: latest

**Comment by compujunk** [comment]
here a screenshot when I create the card
![Naamloos](https://user-images.githubusercontent.com/50024099/66830857-c1410300-ef56-11e9-8048-483cca95059e.jpg)

**Comment by amaximus** [comment]
Googling for an explanation for the above, I can see other custom cards having the same issue: https://github.com/custom-cards/entity-attributes-card/issues/5 also via UI editor.

Is it possible to use the order:
- type: custom:'garbage-collection-card'
  entity: ....
  the rest of config options?

Not sure if UI editor will change the order or not.

**Comment by compujunk** [comment]
I have now:

type: 'custom:garbage-collection-card'
entity: sensor.gft_afval_groen
hide_before: 7
icon_color: green

and then I get this

![Naamloos](https://user-images.githubusercontent.com/50024099/66832568-77f2b280-ef5a-11e9-85be-67be7594172d.jpg)

but I can only put one entity in it which means that I have to make four cards
when I want to create more in the same card I get the message duplicated mapping key

**Comment by amaximus** [comment]
You may include them into an entity card and the entities would be the custom cards.

The garbage-collection-card does not support a list of entities... yet.

**Comment by compujunk** [comment]
when i put it in a entity card i get de error: Expected a value of type `{entity,name,icon} | entity-id` for `entities.0.hide_before` but received `2`.

but it works for now.
hopefully garbage collection cards will get support a list of entities. :)

Thanks
