### ISSUE TITLE
Any way to have the card show after clicked to hide?

### ISSUE THREAD

**Issue by bkr1969** [amaximus/garbage-collection-card#80]
I did not originally set hide_on_click to false, so when I clicked the card it disappeared. Now I cannot get that sensor to show up even if I create a new card with it somewhere. Is there any way to get it back?

**Comment by amaximus** [comment]
hide_on_click is true by default.
The card will reappear once the pick-up date passes if hide_before is not used or hide_before days before the next pick-up date.

**Comment by ikolsteren** [comment]
I must have clicked on when adding and I cant get it back to finish my setup :(
Tried removing and adding everything - hope this is what it is and it will magically come back.  Garbage day is tomorrow

**Comment by amaximus** [comment]
Pls see my previous reply: the card will re-appear once the due date passes.

**Comment by amaximus** [comment]
Any updates on this issue?

**Comment by ikolsteren** [comment]
For me it is resolved thank you. I made sure to set the option to false to make sure no one does again
