### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by X1pheR** [amaximus/garbage-collection-card#81]
**Describe the bug**
The card only shows the date of my sensor. Nothing else. So the name, icon and the text "in x days" are missing.

**To Reproduce**
1. Installed with HACS.
2. Tried to find the custom card in the lovelace UI editor but it was not there. So I added it manually per the example in the docs:
```
type: custom:garbage-collection-card
entity: sensor.hvc_groep_plastic

```
3. See screenshot of how it displays. if I hover before the date a circle slightly shows so the placeholder for the icon is there but just now showing. and so you see the rest is missing.
4. I checked the attributes of the entities I wanted to add but they look fine. See other screenshot.

**Expected behavior**
I expected the garbage entity to show as in the example of the docs.

**Screenshots**
![image](https://user-images.githubusercontent.com/569396/131267202-b4b22632-8372-460b-bce6-e81b066acac0.png)
![image](https://user-images.githubusercontent.com/569396/131267646-3d1242cf-c09f-4367-8f4d-086154782b80.png)

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.19.0
 - Browser: Edge (latest)
 - Browser language: Dutch

**Additional context**
None

**Comment by amaximus** [comment]
The garbage collection custom card works based on and expects sensor state and attributes as provided by custom integration Garbage Collection (https://github.com/bruxy70/Garbage-Collection/).

As per the screenshot you attached it seems that your hvc sensors do not use the above-mentioned custom integration.

**Comment by X1pheR** [comment]
Thank you for the quick response. I thought you could use it with any entity as long as it outputs a timestamp. Maybe update the info to mention that it only works with this specific custom integration?
