### ISSUE TITLE
Icons disappearing after 2021.11.0b2[BUG] 

### ISSUE THREAD

**Issue by Bluhme1** [amaximus/garbage-collection-card#83]
With the new feature of picking icons from a list in the entities, the icons disappear

**Comment by grantclem** [comment]
Having the same issue on beta 2021.11

**Comment by amaximus** [comment]
The card does not modify icons, it takes whatever the custom sensor [1] sets in its attributes [2].

[1] https://github.com/bruxy70/Garbage-Collection/
[2] https://github.com/amaximus/garbage-collection-card/blob/master/dist/garbage-collection-card.js#L31

**Comment by Bluhme1** [comment]
Maybe but I have still lost my icons

**Comment by amaximus** [comment]
Just pushed a release to fix the icons issue in 2021.11.

Please update your card and get back to me with results.

**Comment by Bluhme1** [comment]
Great. It works. Thank you very much

**Comment by caddyblack** [comment]
Having the issue on 2021.11.1
![Screenshot_20211105-192541_Chrome.jpg](https://user-images.githubusercontent.com/48408773/140560392-5b1f2083-c8b8-40c4-8879-111a3a2aab2d.jpg)

After restart core there was no change
After restart of the Supervisor the icons were back.
![Screenshot_20211105-193800_Chrome](https://user-images.githubusercontent.com/48408773/140562166-6e9b02ce-8754-4056-8d94-ceb60558a5f2.jpg)

**Comment by amaximus** [comment]
Maybe flushing the browser cache would have helped.

Anyway, tested in my HA core test environment and the icons were displayed:
![15de6b7c0-9a26-46f6-b60c-db345f7e4f55](https://user-images.githubusercontent.com/2511168/140607704-768ac5eb-5dff-4857-9c56-87d6747ea7fc.png)

**Comment by caddyblack** [comment]
Thank you for your pro-active testing based on my comment. Highly appeciated.
