### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by segabrielssj** [amaximus/garbage-collection-card#85]
**Describe the bug**
My cards disappeared the day for pick up "state"=0. 
One card with another date for pick up was visible "state"= 2. 

the day after pick up my cards were visible again

**To Reproduce**

**Expected behavior**
I expected the cards to be visible with "Red Icons".

**Screenshots**

**Environment (please complete the following information):**
 - Garbage Collection: V3.21
 - Browser: [e.g. chrome, safari], Does not matter, edge, chrome, iphone app
 - Browser language: [e.g. Swedish]

**Additional context**

**Comment by amaximus** [comment]
Didn't you click by mistake on the card that disappeared (and reappeared after the due date)?

The hide_on_click configuration parameter is true by default since it was added [1]

[1] https://github.com/amaximus/garbage-collection-card/releases/tag/1.17.0

**Comment by segabrielssj** [comment]
Hi,

Yes that could be the case 🙁. I changed "hide_on_clic"k to "False", lets wait a week and see whats happening.

BR / Johan
________________________________
Från: Atticus Maximus ***@***.***>
Skickat: den 3 januari 2022 15:20
Till: amaximus/garbage-collection-card ***@***.***>
Kopia: segabrielssj ***@***.***>; Author ***@***.***>
Ämne: Re: [amaximus/garbage-collection-card] [BUG] (Issue #85)


Didn't you click by mistake on the card that disappeared (and reappeared after the due date)?

The hide_on_click configuration parameter is true by default since it was added [1]

[1] https://github.com/amaximus/garbage-collection-card/releases/tag/1.17.0<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famaximus%2Fgarbage-collection-card%2Freleases%2Ftag%2F1.17.0&data=04%7C01%7C%7C9656322b030a49e17e2808d9cec42983%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637768164188510099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EZiPppQjfP7vZowQvllfecyB5tbKJjLV3jvtrEGgwh8%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famaximus%2Fgarbage-collection-card%2Fissues%2F85%23issuecomment-1004124544&data=04%7C01%7C%7C9656322b030a49e17e2808d9cec42983%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637768164188520055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5rPcVreSu%2BnPdzk1%2BN3wiKS%2BlViXX4PjOmPg7OOx%2F8k%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASHSDWTA352BKBMNBBLTRKDUUGWB7ANCNFSM5LCX65LA&data=04%7C01%7C%7C9656322b030a49e17e2808d9cec42983%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637768164188520055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N8z4IXcYH3Bc5DqjKIR89%2BpwBuBsqUtcUhDUxeRs0%2Bs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9656322b030a49e17e2808d9cec42983%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637768164188530012%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dLTWk1f6S4kYAFTofEaqYX2BakDWGYc7dtlAqLaJ9hg%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9656322b030a49e17e2808d9cec42983%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637768164188530012%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QgK1OOYiSWtw23KihbllfPr%2Bj%2FkobUKVh8yZx8dk1sA%3D&reserved=0>.

**Comment by Scoff123** [comment]
If the card has accidentally been clicked before changing the hide_on_click configuration to false, from the default true, is there any way to get the card back again? I hoped setting hide_on_click to false would make the card reappear.....

**Comment by amaximus** [comment]
The card will reappear after the due day or, if hide_before is used, hide_before days before the upcoming due date.

**Comment by Scoff123** [comment]
OK thank you for confirming

**Comment by sycorhsx** [comment]
> The card will reappear after the due day or, if hide_before is used, hide_before days before the upcoming due date.

I accidentally clicked on mine Tuesday (today is Wednesday).  The expire after was set to 23:00 and Collection day was Tuesday.  It did not reappear today.  I added in the hide_on_click: false and hide_before: 6 and it still didn't reappear.  I even tried deleting the button and re-adding it and it still won't show up.  Any suggestions?

**Comment by sycorhsx** [comment]
Never mind. It decided to magically come back after I posted.  *sigh*  I'll figure out HA at some point.
