### ISSUE TITLE
[FeatureRequest]

### ISSUE THREAD

**Issue by Rayeliint** [amaximus/garbage-collection-card#86]
Is it possible to make a configuration to change button size.
Only seem to be able to change icon size and title size?

**Comment by amaximus** [comment]
@Rayeliint this card written some 2 years ago displays information in a table whose layout setting is not really flexible [1]. It would require quite some effort to rewrite it to be more flexibile while keeping it backward compatible.

I'd rather suggest using the Custom Button Card [2] which provides a great flexibility. You may find examples in one of my other repositories [3].

[1] https://www.w3schools.com/cssref/pr_tab_table-layout.asp
[2] https://github.com/custom-cards/button-card
[3] https://github.com/amaximus/met_alerts_hu
