### ISSUE TITLE
wont load

### ISSUE THREAD

**Issue by interbiznw** [amaximus/garbage-collection-card#87]
![image](https://user-images.githubusercontent.com/16450422/150677785-c2b51fa4-3b11-434f-8d94-453145f1a58e.png)

I checked, it downloaded, and added it to resources, it loads when the pages are loaded and i can view file in network tab of files that are loaded so I know the path is right and its loading the code

![image](https://user-images.githubusercontent.com/16450422/150677841-9d324aa6-f188-47dc-9787-551275d664bb.png)

except I get the error above and also the card will not work when manually adding it.

**Comment by amaximus** [comment]
Could you please make sure you use the latest version.
By "manually adding it" you mean it was not installed via HACS?
Please note that after adding the card as resource to configuration.yaml you'll have to restart HA.

The card works on my side:
![garbage](https://user-images.githubusercontent.com/2511168/150680459-f73b1ed6-f8a4-4770-a5c3-046cb56f7847.png)

**Comment by interbiznw** [comment]
no it wasn't added by HACS into resources, probably cause of this
![image](https://user-images.githubusercontent.com/16450422/150705670-819f6c47-1d0a-4582-a378-f133de1099bf.png) 

I will check to make sure up to date and everything else is up to date.

yeah I realize it would have to reboot, which is why i have rebooted several times and also tried to remove and reinstall the card several times from hacs

**Comment by amaximus** [comment]
Any update on this issue?
