### ISSUE TITLE
[BUG] Can't get swedish language to work

### ISSUE THREAD

**Issue by yabbah** [amaximus/garbage-collection-card#90]
**Describe the bug**
I have `hass_lang_priority: true` in the card config. But it wont change to swedish even tho I see the sv.json-file.

**To Reproduce**
Change language of HA to swedish and you'll see it show the date and days in english.

**Expected behavior**
It should show the message in swedish

**Screenshots**
![image](https://user-images.githubusercontent.com/13518966/153214001-c33a7899-cf09-4cb2-8804-b72505a05f98.png)

![image](https://user-images.githubusercontent.com/13518966/153214020-33aafed9-2d06-4db4-ac1b-0adbca80cea0.png)

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.20.1
 - Browser: Chrome
 - Browser language: Swedish

**Additional context**
.

**Comment by amaximus** [comment]
Please make sure you are not using the verbose_state: true.

I could not reproduce the issue with card version 1.20.1 (and Garbage Collection integration on version 4.2) in Chrome:

![garbage_sv](https://user-images.githubusercontent.com/2511168/153268875-23719ef0-3f0e-4ffa-a287-b874ce592db0.png)

If the issue still persists, please provide the version of the Garbage Collection integration and the configuration of one of the garbage sensors.

**Comment by yabbah** [comment]
Ah, it was the sensor in Garabage Collection integration which had verbose_state activated. Thank you for pointing me right :)
