### ISSUE TITLE
[BUG] How do I show a clicked/hide card?

### ISSUE THREAD

**Issue by yabbah** [amaximus/garbage-collection-card#92]
**Describe the bug**

**To Reproduce**
I had this config for a card:

```
type: custom:garbage-collection-card
entity: sensor.karl_2
icon_size: 55px
icon_color: green
due_1_color: orange
due_color: red
hass_lang_priority: true
hide_date: true
```

I clicked and the card disappeared. But I cant find a way to get it show again ? I have tried restart HA, but still hidden.

**Expected behavior**
Want a way to get it show up again.

**Screenshots**

**Environment (please complete the following information):**
Garbage Collection Card version: 1.20.1
Browser: Chrome
Browser language: Swedish

**Additional context**

**Comment by amaximus** [comment]
It's not a bug, it's a feature. :)

The button re-appears once the due date has passed or if hide_before is set then hide_before days before the next due date.
If this behaviour is not needed you may disable it by ```hide_on_click: false```
