### ISSUE TITLE
[BUG] friendly_name not working

### ISSUE THREAD

**Issue by tidusjar** [amaximus/garbage-collection-card#97]
**Describe the bug**
Looking at the code and previous issues, it seems that `friendly_name` should be supported? Currently that does not work

**To Reproduce**
Following config:

```
type: custom:garbage-collection-card
entity: sensor.green
friendly_name: GreenBin
hide_before: 7
icon_color: green
hide_date: true
```
 has the following output
![image](https://user-images.githubusercontent.com/6642220/188955375-1a373ca6-e1c5-4d4e-9d7d-49c50fd3c135.png)

**Expected behavior**
The title of the card to be `GreenBin` and not `Green`

**Environment (please complete the following information):**
 - Garbage Collection Card version: [e.g. 1.15.1] - Latest

**Comment by amaximus** [comment]
Entities have friendly_name attribute, not the UI elements.
The card does not have a friendly_name config parameter, but supports friendly_name attribute of the sensor.
Please define one at entity level (e.g. for sensor.green).

Please get back to me with results.

**Comment by tidusjar** [comment]
Ahhh yeah that works
